version: "3.8"

services:
  client:
    build:
      context: ./workspaces/client
      dockerfile: Dockerfile
      additional_contexts:
        - shared=./workspaces/common
    ports:
     - "8080:8080"
    environment:
      REACT_APP_API_URL: "http://server:3000"

  server:
    build:
      context: ./workspaces/server
      dockerfile: Dockerfile
      additional_contexts:
        - shared=./workspaces/common
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
