/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import  { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { GroupProps } from '@react-three/fiber';
import { useClientStore } from '../store/ClientStore';

type GLTFResult = GLTF & {
    nodes: {
        Cylinder001: THREE.Mesh;
    };
    materials: {
        ['Material.003']: THREE.MeshStandardMaterial;
    };
};

type Props = GroupProps & {
    isSelected: boolean;
    opacity: number;
};

export function Blackcapstone({ isSelected, opacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/blackcapstone.glb') as GLTFResult;

    const material = useMemo(() => {
        const newMaterial = materials['Material.003'].clone();
        newMaterial.opacity = opacity;
        newMaterial.transparent = true;
        return newMaterial;
    }, [materials, opacity]);

    const { selectedColor } = useClientStore();
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                material={material}
                rotation={[0, -0.12, 0]}
                position={[0.25, -0.9, 0.4]}
                scale={[1.647, 0.318, 1.647]}>
                {isSelected && (
                    <meshStandardMaterial attach="material" color={selectedColor} transparent />
                )}
            </mesh>
        </group>
    );
}

useGLTF.preload('/browncapstone.glb');
