/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useMemo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { GroupProps } from '@react-three/fiber';
import { useStore } from 'zustand';
import { useGlobalState } from '../store/store';

type GLTFResult = GLTF & {
    nodes: {
        Cylinder003: THREE.Mesh;
    };
    materials: {
        ['Material.018']: THREE.MeshStandardMaterial;
    };
};

type Props = GroupProps & {
    isSelected: boolean;
    opacity: number;
    isStanding:boolean
};

export function Blackstone({ isSelected, opacity, isStanding, ...props }: Props) {
    const { nodes, materials } = useGLTF('/blackstone.glb') as GLTFResult;

    const { selectedColor } = useGlobalState();

    const material = useMemo(() => {
        const newMaterial = materials['Material.018'];
        newMaterial.opacity = opacity;
        newMaterial.transparent = true;
        return newMaterial;
    }, [materials, opacity]);
    
    const rotation = isStanding ? [-Math.PI / 2, 0, 0] : [0, 0, 0];
    const position = isStanding ? [0.2, 0.3, 0.3] : [0.2, -0.9, 0.3];

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003.geometry}
                material={material}
                position={position}
                scale={[1.647, 0.318, 1.647]}
                rotation={rotation}>
                {isSelected && <meshStandardMaterial attach="material" color={selectedColor} />}
            </mesh>
        </group>
    );
}

useGLTF.preload('/blackstone.glb');
