/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { GroupProps } from '@react-three/fiber';
import { useClientStore } from '../store/ClientStore';

type GLTFResult = GLTF & {
    nodes: {
        Cube004: THREE.Mesh;
    };
    materials: {
        Material: THREE.MeshStandardMaterial;
    };
};

type Props = GroupProps & {
    isSelected: boolean;
    opacity: number;
    isHovered: boolean;
};

export function Whitecapstone({ isSelected, opacity, isHovered, ...props }: Props) {
    const { nodes, materials } = useGLTF('/whitecapstone.glb') as GLTFResult;

    const { getSelectedColor } = useClientStore();
    const selectedColor = getSelectedColor();

    const material = useMemo(() => {
        const newMaterial = materials.Material;
        newMaterial.opacity = opacity;
        newMaterial.transparent = true;
        return newMaterial;
    }, [materials, opacity]);
    return (
        <group {...props} dispose={null}>
            {/* Outline mesh - only visible when selected */}
            {(isSelected || isHovered) && (
                <mesh
                   
                    geometry={nodes.Cube004.geometry}
                    position={[-0.1, -0.9, 0.2]}
                    scale={[1.05, 1.05, 1.05]} // Slightly larger than the main mesh
                >
                    <meshBasicMaterial color={selectedColor} side={THREE.BackSide} />
                </mesh>
            )}

            {/* Main mesh */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                material={material}
                position={[-0.1, -0.9, 0.2]}></mesh>
        </group>
    );
}

useGLTF.preload('/whitecapstone.glb');
