/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import{ useMemo} from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { GroupProps } from '@react-three/fiber';
import { useClientStore } from '../store/ClientStore';

type GLTFResult = GLTF & {
    nodes: {
        Cube004: THREE.Mesh;
    };
    materials: {
        Material: THREE.MeshStandardMaterial;
    };
};

type Props = GroupProps & {
    isSelected: boolean;
    opacity: number;
};

export function Whitecapstone({ isSelected, opacity, ...props }: Props) {
    const { nodes, materials } = useGLTF('/whitecapstone.glb') as GLTFResult;

    const { selectedColor } = useClientStore();
    
    const material = useMemo(() => {
        const newMaterial = materials.Material;
        newMaterial.opacity = opacity;
        newMaterial.transparent = true;
        return newMaterial;
    }, [materials, opacity]);
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                material={material}
                position={[-0.1, -0.9, 0.2]}>
                {isSelected && <meshStandardMaterial attach="material" color={selectedColor} />}
            </mesh>
        </group>
    );
}

useGLTF.preload('/whitecapstone.glb');
